name:                stackage-everything
version:             0.1.0.0
github:              "jared-w/stackage-everything"
license:             BSD3
author:              "Jared Weakly"
maintainer:          "jaredweakly@gmail.com"
copyright:           "Copyright: (c) 2019 Jared Weakly"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Downloads all source code of stackage so that you can build offline.
# category:            Web

description: This small script generates a script to download all the sources of a Stackage LTS release, so they can later be built/installed (including documentation) even when no internet connection is available.

dependencies:
- base >= 4.7 && < 5
- bytestring
- optparse-generic
- megaparsec
- text
- req
- process

library:
  source-dirs: src

executables:
  stackage-everything-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - stackage-everything
