name:                stackage-everything
version:             0.1.0.0
github:              "jared-w/stackage-everything"
license:             BSD3
author:              "Jared Weakly"
maintainer:          "jaredweakly@gmail.com"
copyright:           "Copyright: (c) 2019 Jared Weakly"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jared-w/stackage-everything#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- optparse-generic
- megaparsec
- text
- req
- process

library:
  source-dirs: src

executables:
  stackage-everything-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - stackage-everything

tests:
  stackage-everything-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - stackage-everything
